### ISSUE TITLE
Ban doesn't work properly

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#107]
Actually, Sydney should only respond to messages with the BAN message when that person interacts with Sydney. But she responds to every message with this ban message

**Comment by Luisotee** [comment]
Fixed with #108

**Comment by DinuNuggets** [comment]
I now get this error message:
```
Error: Evaluation failed: Error: MsgKey error: don't have a matching constructor
    at e (https://web.whatsapp.com/:2:3883)
    at new f (https://web.whatsapp.com/app.c84a9214dcf0e06fb30b.js:51:215467)
    at Object.t.createQuotedMsg (https://web.whatsapp.com/app.c84a9214dcf0e06fb30b.js:93:775710)
    at p (https://web.whatsapp.com/app.c84a9214dcf0e06fb30b.js:93:785409)
    at Object.d [as getQuotedMsgObj] (https://web.whatsapp.com/app.c84a9214dcf0e06fb30b.js:93:784832)
    at __puppeteer_evaluation_script__:3:54
    at ExecutionContext._evaluateInternal (/root/sydney-whatsapp-chatbot-2/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/root/sydney-whatsapp-chatbot-2/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at async Message.getQuotedMessage (/root/sydney-whatsapp-chatbot-2/node_modules/whatsapp-web.js/src/structures/Message.js:313:27)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Luisotee** [comment]
Are you sure you did a `git pull`? It's working fine here.

This error seems to be from the [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js) library, maybe you could try reconnecting the whatsapp client or just re cloning it again.

**Comment by DinuNuggets** [comment]
It worked before and suddenly no more. The bot was able to log in successfully and always get the same first 3 messages until this error message came up.

By the way: it suddenly works again without me doing anything

**Comment by Luisotee** [comment]
Well, all is good when it ends good I guess. I will close this as this problem was probably not releated to the ban feature. If it happens again you can create a new issue so that it's better organized.
