### ISSUE TITLE
Update broke everything

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#11]
After I did `git pull` and tried to write a message, this message came up after the AI ​​tried to send the message

```
root/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/structures/Message.js:91
        this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
                                                                          ^
TypeError: data.id.id.substring is not a function
    at Message._patch (/root/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/structures/Message.js:91:75)
    at new Message (/root/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/structures/Message.js:18:24)
    at Client.sendMessage (/root/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/Client.js:699:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by veigamann** [comment]
This is due to whatsapp-web.js being outdated. Try running `yarn install` so it updates automatically. If that doesn't work, run `yarn upgrade-interactive --latest` then select whatsapp-web.js with spacebar and press enter.

**Comment by veigamann** [comment]
To prevent these kinds of issues of happening, I think we need to add a release system, so every release is a fully functional minimum viable product.

**Comment by DinuNuggets** [comment]
GitHub supports such a release system
