### ISSUE TITLE
Sydney with error after scanning QRCODE

### ISSUE THREAD

**Issue by solution01** [veigamann/sydney-whatsapp-chatbot#131]
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66
    at ExecutionContext._evaluateInternal (/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at async Client.initialize (/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/Client.js:278:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[nodemon] app crashed - waiting for file changes before starting...

**Comment by DinuNuggets** [comment]
I have the same problem. I don't think it's the QR code because it crashed while I was normally using it.

First it worked normally, but then it suddenly crashes permanently.

**Comment by DinuNuggets** [comment]
I noticed that there is a commit. #133 Implement that and it works again

**Comment by solution01** [comment]
Thanks @DinuNuggets  😊
