### ISSUE TITLE
Is there any way to use older versions of Sydney?

### ISSUE THREAD

**Issue by Ryzitos** [veigamann/sydney-whatsapp-chatbot#137]
I tried in some ways to use an old version of Sydney, but when he starts logging in with whatsapp an error appears related to the puppeter files, so far I have not been successful even trying on two different versions..

update, I just wanted to show the error that I get when connecting the old versions of Sydney qr code in whatsapp:

```
◒  Waiting for QR code to be scanned..
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66
    at ExecutionContext._evaluateInternal (/root/sydney-whatsapp-chatbot-1.1.0/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/sydney-whatsapp-chatbot-1.1.0/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at async Client.initialize (/root/sydney-whatsapp-chatbot-1.1.0/node_modules/whatsapp-web.js/src/Client.js:278:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Ryzitos** [comment]
I've already been successful

**Comment by Ryzitos** [comment]
I've already been successful.
