### ISSUE TITLE
Error starting Sydney

### ISSUE THREAD

**Issue by solution01** [veigamann/sydney-whatsapp-chatbot#171]
file:///sydney-whatsapp-chatbot/src/handlers/audio-transcription.ts:10
1|sydneybot  | import { randomUUID } from "crypto";
1|sydneybot  |          ^^^^^^^^^^
1|sydneybot  | SyntaxError: The requested module 'crypto' does not provide an export named 'randomUUID'
1|sydneybot  |     at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
1|sydneybot  |     at async ModuleJob.run (internal/modules/esm/module_job.js:143:5)
1|sydneybot  |     at async Loader.import (internal/modules/esm/loader.js:165:24)
1|sydneybot  |     at async Object.loadESM (internal/process/esm_loader.js:68:5)
1|sydneybot  | error Command failed with exit code 1.
1|sydneybot  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1|sydneybot  | [nodemon] app crashed - waiting for file changes before starting...

**Comment by Luisotee** [comment]
Try to delete node_modules and then do yarn install again

**Comment by solution01** [comment]
I carried out the requested procedure, I will analyze it here for a few days and then I will get back to you, thank you for your usual support @Luisotee

**Comment by solution01** [comment]
Problem solved, thanks for your support
