### ISSUE TITLE
It works for a while, then after giving errors and restarting it never comes back 

### ISSUE THREAD

**Issue by Ryzitos** [veigamann/sydney-whatsapp-chatbot#8]
It works indefinitely, sometimes it takes time, sometimes it doesn't. Then when it starts showing errors, which by the way doesn't say what it is exactly, I restart and it never comes back. It even connects but it doesn't go beyond that, it just gives me a bunch of errors in the terminal.

Message received from: 556799855175@c.us
Sydney's response:  Oi, eu sou a Sydney, sua assistente virtual. Estou aqui para te ajudar com o que você precisar. 😊
/workspaces/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/structures/Message.js:91
        this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
                                                                          ^
TypeError: data.id.id.substring is not a function
    at Message._patch (/workspaces/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/structures/Message.js:91:75)
    at new Message (/workspaces/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/structures/Message.js:18:24)
    at Client.sendMessage (/workspaces/sydney-whatsapp-chatbot/node_modules/whatsapp-web.js/src/Client.js:699:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by DinuNuggets** [comment]
Maybe the installation got corrupted.

**Comment by Ryzitos** [comment]
> Maybe the installation got corrupted.

I thought the same thing, until I reinstalled it several times and got the same result, but it could also be a bug directly linked to my whatsapp, I really don't know

**Comment by DinuNuggets** [comment]
Corrupt installation of yarn, node, etc?

**Comment by Ryzitos** [comment]
> Maybe the installation got corrupted.

I find it difficult considering that I reinstalled several times, but maybe so

**Comment by Ryzitos** [comment]
> Corrupt or outdated installation of yarn, node, etc?

That makes sense, I'll check thanks for the idea

**Comment by veigamann** [comment]
Sorry for the delay. I'm also getting these errors. I think that's due to WhatsApp Web update or something. I'll try to fix this today.
